services:
  database:
    image: postgres:alpine
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: carna-database
      POSTGRES_USER: carna
      POSTGRES_PASSWORD: IjSJmKN1fc#DZBL*NHbVoxIh65JvsFFDO@so

  # backend:
  #   container_name: backend
  #   build:
  #     context: backend
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - database
  #   environment:
  #     DATABASE_HOST: database
  #     DATABASE_PORT: 5432
  #     DATABASE_USERNAME: carna
  #     DATABASE_PASSWORD: IjSJmKN1fc#DZBL*NHbVoxIh65JvsFFDO@so
  #     DATABASE_NAME: "carna-database"
