services:
  database:
    image: postgres:alpine
    container_name: database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: carna-database
      POSTGRES_USER: carna
      POSTGRES_PASSWORD: IjSJmKN1fc#DZBL*NHbVoxIh65JvsFFDO@so
