services:
  database:
    image: postgres:alpine
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: carna-database
      POSTGRES_USER: carna
      POSTGRES_PASSWORD: IjSJmKN1fc#DZBL*NHbVoxIh65JvsFFDO@so

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USERNAME: carna
      DATABASE_PASSWORD: IjSJmKN1fc#DZBL*NHbVoxIh65JvsFFDO@so
      DATABASE_NAME: "carna-database"
      ETH_NETWORK: "wss://goerli.infura.io/ws/v3/241d4e2459c14fcfbf62e872ab36e638"
      ETH_CONTRACT: "0x352F8C1f8576183b6c783D3e589aBB69FfBeBc47"
